services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - $PWD/data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rubeckcurtis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Pass123!
    volumes:
      - $PWD/data/pgadmin:/var/lib/pgadmin
