services:
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /Users/curt/code/expense-tracker/db-data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rubeckcurtis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Pass123!
    volumes:
      - /Users/curt/code/expense-tracker/db-data/pgadmin:/var/lib/pgadmin
