### Get Transactions
GET http://localhost:3000/transactions
Content-Type: application/json

### Get One Transaction
GET http://localhost:3000/transactions/3
Content-Type: application/json

### Post Transaction
POST http://localhost:3000/transactions
Content-Type: application/json

{
    "merchant": "hy-vee",
    "amount": 134.99,
    "date": "2024-03-12",
    "userId": "98e12a2b-044d-48ce-9751-2984f590edd4",
    "accountId": 2,
    "categoryId": 1

}

### Put Transaction
Put http://localhost:3000/transactions/4
Content-Type: application/json

{
    "merchant": "target",
    "amount": 19.99,
    "date": "2024-03-20",
    "userId": "98e12a2b-044d-48ce-9751-2984f590edd4",
    "accountId": 2,
    "categoryId": 1

}

### Get Category
GET http://localhost:3000/categories
Content-Type: application/json

### Post Category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "DROP TABLE categories;"
}

### Update Category
PUT http://localhost:3000/categories/7
Content-Type: application/json

{
    "name": "personal",
    "description": "Haircut, makeup, clothes everything else"
}

### Post Account
POST http://localhost:3000/accounts
Content-Type: application/json

{
    "number": 54687982,
    "name": "checking",
    "bank": "FNBO"
}