GET http://localhost:3000/users 
content-type: application/json

{
    "username": "brian"
}

###

POST http://localhost:3000/users
content-type: application/json

{
    "username": "steveie",
    "password": "SuperSecret123"
}


###
POST http://localhost:3000/login
content-type: application/json

{
    "username": "alex",
    "password": "SuperSecret123"
}

###
GET http://localhost:3000/posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNmY1ZWFkZjYtNDYxOC00MDQwLTkwZGQtMDY0NmFkOTZhZjQ4IiwidXNlcm5hbWUiOiJhbGV4IiwicGFzc3dvcmQiOiIkMmIkMTAkQ3lBUFRwMkNJVWp1QzZPQTYuWDFQTzVoeGVieGhibVlNaVdDR0x1STdXdVV3OFBhMFd0aWkiLCJpYXQiOjE3MTA4MTg3OTQsImV4cCI6MTcxMDgxOTA5NH0.AnSVbi9T5wDhHFXzbtBAjRU8hsaVWsUVc9Ksv_LkF3w